# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-29 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yagisan', '0005_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionuser',
            name='is_last',
            field=models.IntegerField(null=True),
        ),
    ]
