# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-30 04:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yagisan', '0006_questionuser_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreQuestionChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('prequestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yagisan.PreQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='PreQuestionUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('prequestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yagisan.PreQuestion')),
                ('prequestionchoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yagisan.PreQuestionChoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yagisan.User')),
            ],
        ),
    ]
