# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-30 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yagisan', '0007_prequestion_prequestionchoice_prequestionuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='FifthQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FifthQuestionUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('fifthquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yagisan.FifthQuestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yagisan.User')),
            ],
        ),
    ]
