# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-31 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yagisan', '0008_fifthquestion_fifthquestionuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialogueUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialogue', models.CharField(max_length=50)),
                ('dialogue_sex', models.IntegerField()),
                ('dialogue_to', models.IntegerField()),
                ('dialogue_type', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yagisan.User')),
            ],
        ),
    ]
