# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yagisan', '0011_questionnaire_questionnairechoice_questionnaireuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaireuser',
            old_name='questionnairechoice',
            new_name='questionnaire_choice',
        ),
        migrations.AddField(
            model_name='questionnaireuser',
            name='sentence',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
