# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yagisan', '0012_auto_20170802_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaireuser',
            name='sentence',
        ),
    ]
